---
title: "HW_02_Report"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(echo = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 6
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Data Import
```{r}
lead_iq = read.csv("~/Desktop/Steinhart_Project_01./Data Raw/lead-iq-01.csv")
#import lead_iq_01 data from local location on computer. 

```


# Update to remove 999 outlier

```{r}
lead_iq = lead_iq %>% filter(IQ<=200)
```


# Graphs

```{r}
#Graph showing IQ by logation status

ggplot(lead_iq, aes(x=Smelter, y=IQ)) + geom_boxplot()

#Table

lead_iq %>% group_by(Smelter) %>% mutate(median_iq=median(IQ, na.rm=TRUE)) %>%  select(median_iq) %>% unique() %>% knitr::kable(., col.names = c("Smelter",
                           "Median IQ"),caption = "Nice Table Title") 
```

# Graph and Table explanation

```{r}
print("The graph that I chose is a boxplot that depicts the IQ data by the variable, Smelter, which consists of two categories: far and near. From the boxplot, we can see that the far category has a few outliers but one clear outlier (999) that is not an accurate representation of an individual's IQ. **After a conversation with the researcher, this outlier has been removed.**  An IQ of 131 or greater is considered very superior (https://www.healthline.com/health/what-is-considered-a-high-iq#whats-a-high-iq). Thus, an IQ of 1000 is likely a data entry error or some other type of error. The table is a simple representation of the median of IQ for each category. The median of the far smelter is 93 and the mean of the near smelter is about 88.") 
```

# Inline Means

```{r}
inline_means = lead_iq %>% group_by(Smelter) %>% mutate(mean_iq=mean(IQ, na.rm=TRUE)) %>% select(mean_iq) %>% unique()
inline_means

```

# The End

```{r}
print("Github seems neat. I'm excited to learn more.")
```

